/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as FocusRouteImport } from './routes/_focus'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppLogRouteImport } from './routes/_app/log'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTodayRouteImport } from './routes/_app/today'
import { Route as AppLessonsIndexRouteImport } from './routes/_app/lessons/index'
import { Route as AppLessonsNewRouteImport } from './routes/_app/lessons/new'
import { Route as AppTopicsIndexRouteImport } from './routes/_app/topics/index'
import { Route as AppTopicsNewRouteImport } from './routes/_app/topics/new'
import { Route as FocusPracticeSessionIdRouteImport } from './routes/_focus/practice/$sessionId'
import { Route as AppLessonsLessonIdIndexRouteImport } from './routes/_app/lessons/$lessonId/index'
import { Route as AppLessonsLessonIdEditRouteImport } from './routes/_app/lessons/$lessonId/edit'
import { Route as AppTopicsTopicIdIndexRouteImport } from './routes/_app/topics/$topicId/index'
import { Route as AppTopicsTopicIdEditRouteImport } from './routes/_app/topics/$topicId/edit'
import { Route as AppLessonsLessonIdFilesFileIdRouteImport } from './routes/_app/lessons/$lessonId/files/$fileId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/_focus',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppLogRoute = AppLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonsIndexRoute = AppLessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonsNewRoute = AppLessonsNewRouteImport.update({
  id: '/lessons/new',
  path: '/lessons/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTopicsIndexRoute = AppTopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => AppRoute,
} as any)
const AppTopicsNewRoute = AppTopicsNewRouteImport.update({
  id: '/topics/new',
  path: '/topics/new',
  getParentRoute: () => AppRoute,
} as any)
const FocusPracticeSessionIdRoute = FocusPracticeSessionIdRouteImport.update({
  id: '/practice/$sessionId',
  path: '/practice/$sessionId',
  getParentRoute: () => FocusRoute,
} as any)
const AppLessonsLessonIdIndexRoute = AppLessonsLessonIdIndexRouteImport.update({
  id: '/lessons/$lessonId/',
  path: '/lessons/$lessonId/',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonsLessonIdEditRoute = AppLessonsLessonIdEditRouteImport.update({
  id: '/lessons/$lessonId/edit',
  path: '/lessons/$lessonId/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppTopicsTopicIdIndexRoute = AppTopicsTopicIdIndexRouteImport.update({
  id: '/topics/$topicId/',
  path: '/topics/$topicId/',
  getParentRoute: () => AppRoute,
} as any)
const AppTopicsTopicIdEditRoute = AppTopicsTopicIdEditRouteImport.update({
  id: '/topics/$topicId/edit',
  path: '/topics/$topicId/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonsLessonIdFilesFileIdRoute =
  AppLessonsLessonIdFilesFileIdRouteImport.update({
    id: '/lessons/$lessonId/files/$fileId',
    path: '/lessons/$lessonId/files/$fileId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/history': typeof AppHistoryRoute
  '/log': typeof AppLogRoute
  '/settings': typeof AppSettingsRoute
  '/today': typeof AppTodayRoute
  '/lessons/new': typeof AppLessonsNewRoute
  '/topics/new': typeof AppTopicsNewRoute
  '/practice/$sessionId': typeof FocusPracticeSessionIdRoute
  '/lessons/': typeof AppLessonsIndexRoute
  '/topics/': typeof AppTopicsIndexRoute
  '/lessons/$lessonId/edit': typeof AppLessonsLessonIdEditRoute
  '/topics/$topicId/edit': typeof AppTopicsTopicIdEditRoute
  '/lessons/$lessonId/': typeof AppLessonsLessonIdIndexRoute
  '/topics/$topicId/': typeof AppTopicsTopicIdIndexRoute
  '/lessons/$lessonId/files/$fileId': typeof AppLessonsLessonIdFilesFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/history': typeof AppHistoryRoute
  '/log': typeof AppLogRoute
  '/settings': typeof AppSettingsRoute
  '/today': typeof AppTodayRoute
  '/lessons/new': typeof AppLessonsNewRoute
  '/topics/new': typeof AppTopicsNewRoute
  '/practice/$sessionId': typeof FocusPracticeSessionIdRoute
  '/lessons': typeof AppLessonsIndexRoute
  '/topics': typeof AppTopicsIndexRoute
  '/lessons/$lessonId/edit': typeof AppLessonsLessonIdEditRoute
  '/topics/$topicId/edit': typeof AppTopicsTopicIdEditRoute
  '/lessons/$lessonId': typeof AppLessonsLessonIdIndexRoute
  '/topics/$topicId': typeof AppTopicsTopicIdIndexRoute
  '/lessons/$lessonId/files/$fileId': typeof AppLessonsLessonIdFilesFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_focus': typeof FocusRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/log': typeof AppLogRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/today': typeof AppTodayRoute
  '/_app/lessons/new': typeof AppLessonsNewRoute
  '/_app/topics/new': typeof AppTopicsNewRoute
  '/_focus/practice/$sessionId': typeof FocusPracticeSessionIdRoute
  '/_app/lessons/': typeof AppLessonsIndexRoute
  '/_app/topics/': typeof AppTopicsIndexRoute
  '/_app/lessons/$lessonId/edit': typeof AppLessonsLessonIdEditRoute
  '/_app/topics/$topicId/edit': typeof AppTopicsTopicIdEditRoute
  '/_app/lessons/$lessonId/': typeof AppLessonsLessonIdIndexRoute
  '/_app/topics/$topicId/': typeof AppTopicsTopicIdIndexRoute
  '/_app/lessons/$lessonId/files/$fileId': typeof AppLessonsLessonIdFilesFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/login'
    | '/$'
    | '/history'
    | '/log'
    | '/settings'
    | '/today'
    | '/lessons/new'
    | '/topics/new'
    | '/practice/$sessionId'
    | '/lessons/'
    | '/topics/'
    | '/lessons/$lessonId/edit'
    | '/topics/$topicId/edit'
    | '/lessons/$lessonId/'
    | '/topics/$topicId/'
    | '/lessons/$lessonId/files/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/login'
    | '/$'
    | '/history'
    | '/log'
    | '/settings'
    | '/today'
    | '/lessons/new'
    | '/topics/new'
    | '/practice/$sessionId'
    | '/lessons'
    | '/topics'
    | '/lessons/$lessonId/edit'
    | '/topics/$topicId/edit'
    | '/lessons/$lessonId'
    | '/topics/$topicId'
    | '/lessons/$lessonId/files/$fileId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_focus'
    | '/access-denied'
    | '/login'
    | '/_app/$'
    | '/_app/history'
    | '/_app/log'
    | '/_app/settings'
    | '/_app/today'
    | '/_app/lessons/new'
    | '/_app/topics/new'
    | '/_focus/practice/$sessionId'
    | '/_app/lessons/'
    | '/_app/topics/'
    | '/_app/lessons/$lessonId/edit'
    | '/_app/topics/$topicId/edit'
    | '/_app/lessons/$lessonId/'
    | '/_app/topics/$topicId/'
    | '/_app/lessons/$lessonId/files/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  FocusRoute: typeof FocusRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_focus': {
      id: '/_focus'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/log': {
      id: '/_app/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof AppLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/today': {
      id: '/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lessons/': {
      id: '/_app/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof AppLessonsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lessons/new': {
      id: '/_app/lessons/new'
      path: '/lessons/new'
      fullPath: '/lessons/new'
      preLoaderRoute: typeof AppLessonsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/topics/': {
      id: '/_app/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof AppTopicsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/topics/new': {
      id: '/_app/topics/new'
      path: '/topics/new'
      fullPath: '/topics/new'
      preLoaderRoute: typeof AppTopicsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_focus/practice/$sessionId': {
      id: '/_focus/practice/$sessionId'
      path: '/practice/$sessionId'
      fullPath: '/practice/$sessionId'
      preLoaderRoute: typeof FocusPracticeSessionIdRouteImport
      parentRoute: typeof FocusRoute
    }
    '/_app/lessons/$lessonId/': {
      id: '/_app/lessons/$lessonId/'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId/'
      preLoaderRoute: typeof AppLessonsLessonIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lessons/$lessonId/edit': {
      id: '/_app/lessons/$lessonId/edit'
      path: '/lessons/$lessonId/edit'
      fullPath: '/lessons/$lessonId/edit'
      preLoaderRoute: typeof AppLessonsLessonIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/topics/$topicId/': {
      id: '/_app/topics/$topicId/'
      path: '/topics/$topicId'
      fullPath: '/topics/$topicId/'
      preLoaderRoute: typeof AppTopicsTopicIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/topics/$topicId/edit': {
      id: '/_app/topics/$topicId/edit'
      path: '/topics/$topicId/edit'
      fullPath: '/topics/$topicId/edit'
      preLoaderRoute: typeof AppTopicsTopicIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lessons/$lessonId/files/$fileId': {
      id: '/_app/lessons/$lessonId/files/$fileId'
      path: '/lessons/$lessonId/files/$fileId'
      fullPath: '/lessons/$lessonId/files/$fileId'
      preLoaderRoute: typeof AppLessonsLessonIdFilesFileIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppLogRoute: typeof AppLogRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTodayRoute: typeof AppTodayRoute
  AppLessonsNewRoute: typeof AppLessonsNewRoute
  AppTopicsNewRoute: typeof AppTopicsNewRoute
  AppLessonsIndexRoute: typeof AppLessonsIndexRoute
  AppTopicsIndexRoute: typeof AppTopicsIndexRoute
  AppLessonsLessonIdEditRoute: typeof AppLessonsLessonIdEditRoute
  AppTopicsTopicIdEditRoute: typeof AppTopicsTopicIdEditRoute
  AppLessonsLessonIdIndexRoute: typeof AppLessonsLessonIdIndexRoute
  AppTopicsTopicIdIndexRoute: typeof AppTopicsTopicIdIndexRoute
  AppLessonsLessonIdFilesFileIdRoute: typeof AppLessonsLessonIdFilesFileIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppLogRoute: AppLogRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTodayRoute: AppTodayRoute,
  AppLessonsNewRoute: AppLessonsNewRoute,
  AppTopicsNewRoute: AppTopicsNewRoute,
  AppLessonsIndexRoute: AppLessonsIndexRoute,
  AppTopicsIndexRoute: AppTopicsIndexRoute,
  AppLessonsLessonIdEditRoute: AppLessonsLessonIdEditRoute,
  AppTopicsTopicIdEditRoute: AppTopicsTopicIdEditRoute,
  AppLessonsLessonIdIndexRoute: AppLessonsLessonIdIndexRoute,
  AppTopicsTopicIdIndexRoute: AppTopicsTopicIdIndexRoute,
  AppLessonsLessonIdFilesFileIdRoute: AppLessonsLessonIdFilesFileIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface FocusRouteChildren {
  FocusPracticeSessionIdRoute: typeof FocusPracticeSessionIdRoute
}

const FocusRouteChildren: FocusRouteChildren = {
  FocusPracticeSessionIdRoute: FocusPracticeSessionIdRoute,
}

const FocusRouteWithChildren = FocusRoute._addFileChildren(FocusRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  FocusRoute: FocusRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
